trydjango19/posts/api/urls.py
from django.conf.urls import url

from posts.api.views import (
    PostListAPIView,
    PostCreateAPIView,
    PostDetailAPIView,
    PostDeleteAPIView,
    PostUpdateAPIView,
)

urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),
    # restframework treats pk as the default search value
    url(r'^(?P<pk>\d+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/edit/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/delete/$', PostDeleteAPIView.as_view(), name="delete"),
]

trydjango19/posts/urls.py
from django.conf.urls import url

from .views import (
    post_list,
    post_detail,
    post_create,
    post_update,
    post_delete
)

urlpatterns = [
    url(r'^$', post_list, name="list"),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name="delete"),
]

trydjango19/trydjango19/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

from accounts.views import (
    login_view,
    logout_view,
    register_view
)

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include("posts.urls", namespace="posts")),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

trydjango19/posts/models.py
import os

from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.safestring import mark_safe
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.contrib.contenttypes.models import ContentType


from markdown_deux import markdown

from comments.models import Comment
from .utils import get_read_time


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super().filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, filename):
    # filebase, extension = filename.split(".")
    # path = os.path.join(instance.id, instance.id)
    # path = ".".join(path, extension)
    if instance.id:
        path = os.path.join(instance.id, filename)
    else:
        path = filename
    return path


class Post(models.Model):

    class Meta:
        ordering = ["timestamp", "-updated"]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.TimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.__str__()

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={'slug': self.slug})

    def get_markdown(self):
        content = self.content
        return mark_safe(markdown(content))

    @property
    def comments(self):
        instance = self
        qs = Comment.objects.filter_by_instance(instance)
        return qs

    @property
    def get_content_type(self):
        instance = self
        content_type = ContentType.objects.get_for_model(instance.__class__)
        return content_type


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "{}-{}".format(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        html_string = instance.get_markdown()
        read_time = get_read_time(html_string)
        instance.read_time = read_time


pre_save.connect(pre_save_post_receiver, sender=Post)

trydjango19/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish"
        ]

trydjango19/posts/api/views.py
from django.db.models import Q
from rest_framework.generics import (
    CreateAPIView,
    ListAPIView,
    RetrieveUpdateAPIView,
    RetrieveAPIView,
    DestroyAPIView,
)

from rest_framework.filters import SearchFilter, OrderingFilter

from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)

from posts.models import Post
from posts.api.serializers import (
    PostListSerializer,
    PostDetailSerializer,
    PostCreateUpdateSerializer
)
from posts.api.permissions import IsOwnerOrReadOnly
from posts.api.pagination import PostLimitOffsetPagination, PostPageNumberPagination


class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    ordering = 'title'
    search_fields = ['title', 'content', 'user__first_name']
    pagination_class = PostPageNumberPagination

    def get_queryset(self, *args, **kwargs):
        post_list = Post.objects.all()
        search_query = self.request.GET.get('search_query')
        if search_query:
            post_list = post_list.filter(
                Q(title__icontains=search_query) |
                Q(content__icontains=search_query) |
                Q(user__first_name__icontains=search_query) |
                Q(user__last_name__icontains=search_query)
            ).distinct()
        return post_list


class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

trydjango19/posts/views.py
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from django.db.models import Q
from django.utils import timezone

from comments.models import Comment
from comments.forms import CommentForm
from .models import Post
from .forms import PostForm


def post_create(request):

    if not request.user.is_authenticated():
        raise Http404

    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        post = form.save(commit=False)
        post.user = request.user
        post.save()
        messages.success(request, "Post successfull created.")
        return redirect(post.get_absolute_url())
    context = {"form": form}
    return render(request, "post_form.html", context)


def post_detail(request, slug=None):

    post = get_object_or_404(Post, slug=slug)

    if post.draft or post.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404

    initial_comment_data = {
        "content_type": post.get_content_type,
        "object_id": post.id
    }

    comments = Comment.objects.filter_by_instance(post)
    comment_form = CommentForm(request.POST or None,
                               initial=initial_comment_data)

    if comment_form.is_valid() and request.user.is_authenticated():
        cont_type = comment_form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=cont_type)
        obj_id = comment_form.cleaned_data.get('object_id')
        cont_data = comment_form.cleaned_data.get('content')
        parent_obj = None

        try:
            parent_id = int(request.POST.get('parent_id'))
        except TypeError:
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
                        user=request.user,
                        content_type=content_type,
                        object_id=obj_id,
                        content=cont_data,
                        parent=parent_obj,
            )

        if created:
            print("New comment successfully created.")
        return redirect(new_comment.content_object.get_absolute_url())

    context = {
        "post": post,
        "comments": comments,
        "comment_form": comment_form
    }
    return render(request, "post_detail.html", context)


def post_list(request):
    # post_list = Post.objects.all().order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        post_list = Post.objects.all()
    else:
        post_list = Post.objects.active()

    search_query = request.GET.get('search_query')
    if search_query:
        post_list = post_list.filter(
            Q(title__icontains=search_query) |
            Q(content__icontains=search_query) |
            Q(user__first_name__icontains=search_query) |
            Q(user__last_name__icontains=search_query)
        ).distinct()

    paginator = Paginator(post_list, 10)
    page_request_var = "page"
    page = request.GET.get(page_request_var, 1)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, "post_list.html", {"posts": posts,
                                              "page_request_var": "page"})


def post_update(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        post = form.save(commit=False)
        post.save()
        messages.success(request, "Post successfull saved.")
        return redirect(post.get_absolute_url())
    context = {
        "post": post,
        "form": form
    }
    return render(request, "post_form.html", context)


def post_delete(request, slug):
    post = get_object_or_404(Post, slug=slug)
    post.delete()
    messages.success(request, "Post successfull deleted.")
    return redirect("posts:list")

trydjango19/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Try Django{% endblock head_title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    {% block head_extra %} {% endblock head_extra %}
</head>
    <body>

    {% include "messages_display.html" %}


    <div class="container">
        <ol class="breadcrumb menu-items">
            <li class="menu-list-item"><a href="{% url 'posts:list' %}">Home</a></li>

            {% block post_detail_link %}
            {% endblock %}
            {% if request.user.is_authenticated %}
                <li class="menu-list-item pull-right"><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li class="menu-list-item pull-right"><a href="{% url 'register' %}">Register</a></li>
                <li class="menu-list-item pull-right"><a href="{% url 'login' %}">Login</a></li>
            {% endif %}
            
        </ol>
        {% block content %}
        {% endblock content %}
    </div>

    <div id="fb-root"></div>

    
    <script   src="https://code.jquery.com/jquery-2.2.2.min.js"   integrity="sha256-36cp2Co+/62rEAAYHLmRCPIych47CvdM+uTBJwSzWjI="   crossorigin="anonymous"></script>    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            // $(".content-markdown").each(function(){
            //     currentBlock = $(this);
            //     var postContent = currentBlock.text();
            //     var markedContent = marked(postContent);
            //     currentBlock.html(markedContent);                
            // });
            $(".post-detail-item img").each(function(){
                currentImg = $(this);
                currentImg.addClass("img-responsive");                
            });

            var titleInput = $("#id_title");
            var contentInput = $("#id_content");

            setTitle(titleInput.val())
            setContent(contentInput.val())

            titleInput.keyup(function(){
                setTitle(titleInput.val())
            });


            function setTitle(value) {
                $("#preview-title").text(value);
            }

            function setContent(value){
                var markedContent = marked(value || '');
                $("#preview-content").html(markedContent);
                $("#preview-content img").each(function(){
                    $(this).addClass("img-responsive");
                })
            }

            contentInput.keyup(function() {
                setContent(contentInput.val());
            });

            // setContent(contentInput.val());


        });
    </script>
    </body>
</html>

trydjango19/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}

    {{ post.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3 ">

        <p>{{ comment.content }} </p>
        <footer>via {{ comment.user }} | {{ comment.timestamp | timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %}  | {% endif %}
        {% if request.user == comment.user %}
            <a href="{{ comment.get_absolute_url }}/delete">Remove</a>
        {% endif %}
        </footer>
        <hr>

        <div>
           {% for child_comment in comment.children %}
                <blockquote>
                    <p>{{ child_comment.content }} </p>
                    <footer>via {{ child_comment.user }} {{ child_comment.timestamp | timesince }} ago
                    {% if request.user == child_comment.user %}
                        <a href="{{ child_comment.get_absolute_url }}/delete">Remove</a>
                    {% endif %}
                    </footer>
                </blockquote>                
            {% endfor %}                            
        </div>

    {% if request.user.is_authenticated %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form |crispy }}
        <input type="hidden" name="parent_id" value='{{ comment.id }}'>
        <input type="submit" value="Reply" class="btn btn-default">
    </form>
    {% else %}
        <p class="not-logged-in-comment-msg">You must be logged in to comment</p>
    {% endif %}

</div>
{% include "facebook_sdk.html" %}

{% endblock content %}

trydjango19/templates/confirm_comment_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}

    {{ post.title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}

<div class="col-sm-6 col-sm-offset-3 ">
    <h1>Confirm comment deletion</h1>

    <form action="" method="POST">
        <p>Are you sure you want to delete: "{{ comment.content }}"?</p>
        {% csrf_token %}
        <input type="submit" value="Confirm" class="btn btn-warning">
        <a href="{{ comment.get_absolute_url }}" class="btn btn-default">Cancel</a>
    </form>


</div>
{% include "facebook_sdk.html" %}

{% endblock content %}

trydjango19/templates/facebook_sdk.html
<script>
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v2.5";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>

trydjango19/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Start page.</title>
</head>
<body>
    {% if posts %}
    <ul>
        {% for post in posts %}
            <li>
                <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
                <br> 
                {{ post.content }}
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <h2>No posts available</h2>
    {% endif %}
</body>
</html>

trydjango19/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h2>Login:</h2>
<hr>

<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-default" value="Login">    
</form>    
</div>

{% endblock content %}

trydjango19/templates/messages_display.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

trydjango19/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ post.title }} | {{ block.super }}
{% endblock head_title %}

{% block post_detail_link %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
{% endblock %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3 ">
    
    <h1>{{ post.title }} <small>{% if post.draft %}<span style="color:red">Draft</span>{% endif %}{{ post.publish }}</small></h1>
    <p>Expected reading time: {% if post.read_time|time:"i" <= "01" %} < 1 minute {% else %} {{ post.read_time | time:"i"}} min {% endif %}</p>
    {% if  post.user.get_full_name %}
        <p>Author: {{ post.user.get_full_name }}</p>
        <span><a href="{{ request.build_absolute_uri }}edit">Edit</a></span>
    {% endif %}
    <div class="post-content">
<div class="post-text post-detail-item">
    {{ post.get_markdown }}
</div>
        {% if post.image %}
            <img src="{{ post.image.url }}" alt="" class="img-responsive">
        {% endif %}
        <span>{{ post.updated }}</span>

        <div>
            <p class="lead">Comments</p>
                <hr>
                {% if request.user.is_authenticated %}
                <form action="" method="POST">
                    {% csrf_token %}
                    {{ comment_form |crispy }}
                    <input type="submit" value="Send comment" class="btn btn-default">
                </form>
                {% else %}
                    <p class="not-logged-in-comment-msg">You must be logged in to comment</p>
                {% endif %}
                {% for comment in comments %}
                    <blockquote class="post-detail__comment-content">
                        <p>{{ comment.content }} </p>
                        <footer>via {{ comment.user }} {{ comment.timestamp | timesince }} ago | {% if comment.children.count > 0 %} Comment{% if comment.children.count > 1 %}s{% endif %} {{ comment.children.count }} | {% endif %}
                            <a class="comment-reply-btn" href="#">Reply</a> | 
                            <a href="{{ comment.get_absolute_url }}">Thread</a>
                            {% if request.user == comment.user %}
                                <a href="{{ comment.get_delete_url }}">Remove</a>
                            {% endif %}
                        </footer>
                        <div class="comment-replies">
                       {% for child_comment in comment.children %}
                            <blockquote>
                                <p>{{ child_comment.content }} </p>
                                <footer>via {{ child_comment.user }} {{ child_comment.timestamp | timesince }} ago
                                    {% if request.user == comment.user %}
                                        <a href="{{ comment.get_delete_url }}">Remove</a>
                                    {% endif %}
                                </footer>
                            </blockquote>                
                        {% endfor %}                            
                        </div>

                {% if request.user.is_authenticated %}
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ comment_form |crispy }}
                        <input type="hidden" name="parent_id" value='{{ comment.id }}'>
                        <input type="submit" value="Reply" class="btn btn-default">
                    </form>
                {% else %}
                    <p class="not-logged-in-comment-msg">You must be logged in to comment</p>
                {% endif %}
                    </blockquote>
                {% endfor %}
        </div>

    </div>   

    <p>
       <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
    </p>


<!-- {% include "facebook_sdk.html" %} -->

{% endblock content %}

trydjango19/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class="col-sm-6">
    <h2>Preview</h2>
    <div class="content-preview">
        <h3 id="preview-title"></h3>
        <p id="preview-content"></p>
    </div>
</div>
<div class="col-sm-6">
<h2>Create Post:</h2>

<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-default" value="Create post">    
</form>    
</div>

{% endblock content %}

trydjango19/templates/post_list.html
{% extends "base.html" %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h1>List of posts</h1>
<form action="" method="GET">
    <div class="input-group search-input-group">
        <input class="form-control" type="text" name="search_query" placeholder="Search posts" value='{{ request.GET.search_query }}'>
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </span>
    </div>
</form>
    {% if posts %}
        {% for post in posts %}
        <div class="row">
            <div class="col-sm-12">
                <div class="thumbnail">
                    {% if post.image %}
                        <img src="{{ post.image.url }}" alt="" class="img-responsive">
                    {% endif %}

                    <div class="caption post-detail-item">
                        {% if post.draft %}<h3 style="color: red">Draft</h3>{% endif %}
                        <h3>
                            <a href='{{ post.get_absolute_url }}'>{{ post.title }}</a>
                            <small>{{ post.publish | timesince }} ago</small>
                        </h3>
                        {% if  post.user.get_full_name %}
                            <p>Author: {{ post.user.get_full_name }}</p>
                        {% endif %}
                        {{ post.get_markdown | truncatewords_html:29 }}
                        <p>
                            <a href="{{ post.get_absolute_url }}" class="btn btn-primary" role="button">View</a>
                            <!-- <a href="#" class="btn btn-default" role="button">Edit</a> -->
                        </p>
                    </div>
                </div>
            </div>
        <hr/>
        </div>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if posts.has_previous %}
                    <a href="?{{ page_request_var }}={{ posts.previois_page_number }}&search_query={{ request.GET.search_query }}">previous</a>
                {% endif %}
            </span>

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?{{ page_request_var }}={{ posts.next_page_number }}&search_query={{ request.GET.search_query }}">next</a>
            {% endif %}
        </div>
</div>

    {% else %}
        <h2>No posts available</h2>
    {% endif %}    
{% endblock content %}

trydjango19/templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
<div class="col-sm-6 col-sm-offset-3">
<h2>Register:</h2>
<hr>

<form method="POST" action="" enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form | crispy }}
    <input type="submit" class="btn btn-default" value="Register">    
</form>    
</div>

{% endblock content %}